# Используем официальный образ MySQL
FROM arm64v8/mysql
# Копируем файл с инициализацией базы данных
COPY init.sql /docker-entrypoint-initdb.d/

# Устанавливаем переменные окружения для MySQL
ENV MYSQL_ROOT_PASSWORD='Pro2216450788_'
ENV MYSQL_DATABASE='LinkUpDb'
ENV MYSQL_USER='root'
ENV MYSQL_PASSWORD='Pro2216450788_'

# Запускаем MySQL
CMD ["mysqld"]